version: '3.9'

services:
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app/
    command: sh -c "while true; do sleep 1; done"
    restart: on-failure:4
    depends_on:
      - firestore_emulator

  firestore_emulator:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID=dummy-project-id
      - PORT=8200
    ports:
      - 8200:8200